
// SlkConstants.cs - generated by the SLK parser generator 

namespace Rotfl {

class SlkConstants {

public const short  HAI_ = 257;
public const short  STATEMENT_SEPARATOR_ = 258;
public const short  KTHXBYE_ = 259;
public const short  SUM_ = 260;
public const short  OF_ = 261;
public const short  DIFF_ = 262;
public const short  PRODUKT_ = 263;
public const short  QUOSHUNT_ = 264;
public const short  MOD_ = 265;
public const short  BIGGR_ = 266;
public const short  SMALLR_ = 267;
public const short  IDENTIFIER_ = 268;
public const short  NUMBR_ = 269;
public const short  NUMBAR_ = 270;
public const short  YARN_ = 271;
public const short  AN_ = 272;
public const short  I_HAS_A_ = 273;
public const short  ITZ_ = 274;
public const short  VISIBLE_ = 275;
public const short  GIMME_ = 276;
public const short  END_OF_SLK_INPUT_ = 277;


public const short  NT_LOLCODE_ = 2049;
public const short  NT_LOLCODE_BODY_ = 2050;
public const short  NT_STATEMENT_WITH_SEPARATOR_ = 2051;
public const short  NT_STATEMENT_ = 2052;
public const short  NT_BINARY_OP_ = 2053;
public const short  NT_VALUE_ = 2054;
public const short  NT_EXPRESSION_ = 2055;
public const short  NT_DECLARATION_ = 2056;
public const short  NT_STDIO_ = 2057;
public const short  NT_STATEMENT_WITH_SEPARATOR_STAR_ = 2058;
public const short  NT_ITZ_EXPRESSION_OPT_ = 2059;
public const short  NT_EXPRESSION_STAR_ = 2060;


};


}
